name: MONO everyday beta

on:
    push:
        branches:    
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout master
            uses: actions/checkout@v2
            with:
                ref: master

        -   name: Set up Python 3.9
            uses: actions/setup-python@v1
            with:
                python-version: 3.9.6

        -   name: Download MONO
            run: |
                pip install -r requirements.txt
                python ./main.py

        -   name: Add & Commit
            uses: EndBug/add-and-commit@v7.2.1
            with:
                author_name: borber
                author_email: borber.drum@gmail.com

        -   name: Push changes
            uses: ad-m/github-push-action@master
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: master